### PR TITLE
Filter fixes

### PR DESCRIPTION
**Pull request by panosru**
1. Fixed filesizeformat filter. Returned NaN

### CODE REVIEW

**Comment by panosru** [comment]
float filter returns NaN instead of 0.0

your source code looks like this:

```
    $float: function (value)
        res = parseFloat value
        return 0.0 if res is NaN
        return res
```

which compiles to js :

``` js
    $float: (function(){
      function $float(value){
        var res;
        res = parseFloat(value);
        if (res === NaN) {
          return 0.0;
        }
        return res;
      }
      return $float;
    }())
```

Instead of `res === NaN`, `isNaN(res)` should be used, also it is easy to add a default return type if we want to alter `0.0`.

``` js
    $float: (function(){
      function $float(value, def){
        var res;
        var def = def || 0.0;
        res = parseFloat(value);
        if (isNaN(res)) {
          return def;
        }
        return res;
      }
      return $float;
    }())
```

Also this does not return a float `0.0` but an int `0`.

btw, sorry for my ignorance, what are .co files?

**Comment by panosru** [comment]
a better `reverse` filter:

``` js
    $reverse: (function(){
      function $reverse(arr, preserve_array){
        var preserve_array = preserve_array || true;
        var new_arr = arr;
        switch (typeof arr) {
          case 'number':
            new_arr = new_arr.toString();

          case 'string':
            new_arr = new_arr.split('');

          case 'array':
            new_arr = new_arr.splice(0);
            break;

          default:
            throw new Error('Unsupported type "' + typeof arr + '" for reverse');
        }
        new_arr.reverse();
        return (preserve_array) ? new_arr.join('') : new_arr;
      }
      return $reverse;
    }())
```

**Comment by ceymard** [comment]
Hello,

Unfortunately, I cannot merge it this way, since the source is done in coco and not in javascript.

If you're interested in contributing, then I'll just finish the clean translation in javascript that I had started 
(I don't have much time to myself lately...)

**Comment by ceymard** [comment]
Ah sorry, didn't see the question : the .co files are the original files.

It's a langage derived from coffeescript, called coco. It's on github in satyr/coco.

I used to use it a lot, but nowadays I switched back to pure javascript.

**Comment by panosru** [comment]
@ceymard thank you for your replies :) I'll wait for the pure javascript implementation then to contribute :)

Thanks :)

**Comment by panosru** [comment]
btw the pull request I made is on coco not on js :)

**Pull request closed without merging**
